###############################################
# 
# Creates an mySQL dataabase 
# 											  
###############################################

# setup
 FROM ubuntu:latest
 MAINTAINER javakin danielharaldson@yahoo.com
 

# run container in forground

 
 
 
 
 
 
 
 
 
 
