###############################################
#
# Creates an apachie-2 server
#
###############################################

# setup
 FROM tutum/apache-php
 MAINTAINER javakin danielharaldson@yahoo.com


# run container in forground
#CMD apachectl -D FOREGROUND

